# 线上配置文件
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp14kjh9te20c7in93o.mysql.rds.aliyuncs.com/hlbi?useSSL=false
    username: hlllg
    password: HGL2020mm
  session:
    timeout: 86400
    store-type: redis
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 2
    host: 8.138.107.109
    port: 6379
    timeout: 5000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 生产环境关闭日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.hlllg.springbootinit.controller
# 鱼聪明AI 配置
yuapi:
  client:
    access-key: l99kgzy82u54guowqfscahsytwwbjiwe
    secret-key: ufksqyoucjx8bhafn5ofgh3eorfw4ao5
server:
  address: 0.0.0.0
  servlet:
    session:
      cookie:
        domain: hlllg.cn
        same-site: lax
        secure: false
